version: '3'
services:
  radius:
    build: .
    volumes:
      - ./raddb/radiusd.conf:/etc/freeradius/3.0/radiusd.conf:ro
      - ./raddb/clients.conf:/etc/freeradius/3.0/clients.conf:ro
      - ./raddb/mods-config/files/authorize:/etc/freeradius/3.0/mods-config/files/authorize:ro
      - ./raddb/mods-enabled/eap:/etc/freeradius/3.0/mods-enabled/eap:ro
      - ./raddb/certs/ca.cnf:/etc/freeradius/3.0/certs/ca.cnf:ro
      - ./raddb/certs/server.cnf:/etc/freeradius/3.0/certs/server.cnf:ro
      - ./raddb/certs/client.cnf:/etc/freeradius/3.0/certs/client.cnf:ro
    ports:
      - 1812-1813:1812-1813/udp

  # test:
  #   build: .
  #   depends_on:
  #     - radius
  #   tty: true
  #   stdin_open: true
  #   command: bash
